### ISSUE TITLE
Bad link to the UML Diagram

### ISSUE THREAD

**Issue by jmgimeno** [UdL-EPS-SoftArch/AcademicRecruitAPI-GEI#41]
The link to the UML diagram in the README.md does not work.  

It responds with: Error Fetching Resource.

**Comment by latra** [comment]
The current plantUML URL was pointing to dev branch.

Dev branch has been deleted and that's why readme are not able to resolve the uml.

Is necesary change the readmeURL to 
http://www.plantuml.com/plantuml/uml/3SGn3i8m3030hy034kzi6IfKYQ6YuW71CSHIubIEBRvFRxWh2pOlvDekrUoODm3Dl_Xbg_xsIOf3ZCGYZWwlyWZBjeTzV2mfLaYO2tN69w4wMzhMS5zMw9a5lBTudFq1
